version: "3.8"
services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    stop_grace_period: 2m
    volumes:
      - mongo_data:/data/db   # ✅ use named volume
      - ./backend/data/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    expose:
      - "8080"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "80:80"

volumes:
  mongo_data:   # ✅ defined named volume
